"""content.py — bibliotecas de conteúdo do produto (restauradas do dataset publicado).

Dados de apoio do produto: metadados de setor, vocabulário controlado e as
bibliotecas de obrigações, riscos, oportunidades e ações recomendadas por tema.
Os textos são conteúdo editorial do produto (análise/recomendação) e nunca
substituem a fonte oficial citada em cada evento.
"""

# --------------------------------------------------------------- funções
FUNCTIONS = {'ai-governance': 'AI Governance',
 'clinical': 'Assuntos clínicos / regulatórios',
 'compliance': 'Compliance',
 'cybersecurity': 'Cybersecurity',
 'data-governance': 'Data Governance',
 'dpo': 'Data Protection Officer',
 'engineering': 'Engenharia / ML',
 'finance': 'Financeiro',
 'general-counsel': 'General Counsel',
 'government-affairs': 'Government Affairs',
 'hr': 'Recursos Humanos',
 'legal': 'Jurídico',
 'marketing': 'Marketing',
 'privacy': 'Privacy',
 'procurement': 'Compras e fornecedores',
 'product': 'Product',
 'public-policy': 'Public Policy',
 'regulatory-affairs': 'Regulatory Affairs',
 'risk': 'Risk',
 'strategy': 'Strategy'}

# ------------------------------------------------------------ tipos de empresa
COMPANY_TYPES = {'ai-deployer': 'Operador (deployer) de sistema de IA',
 'ai-system-provider': 'Provedor de sistema de IA',
 'cloud-infra': 'Provedor de cloud, infraestrutura ou capacidade computacional',
 'digital-platform': 'Plataforma digital / marketplace',
 'financial-institution': 'Instituição financeira regulada',
 'gpai-provider': 'Provedor de modelo de uso geral (GPAI)',
 'health-provider': 'Prestador de saúde ou dispositivo médico',
 'importer-distributor': 'Importador ou distribuidor',
 'insurer': 'Seguradora',
 'large-enterprise': 'Grande empresa',
 'listed-company': 'Empresa com capital aberto',
 'manufacturer': 'Indústria transformadora',
 'ngo': 'Organização sem fins lucrativos',
 'non-eu-provider': 'Empresa fora da UE com oferta no mercado da União',
 'open-source': 'Desenvolvedor de código aberto',
 'professional-services': 'Serviços profissionais (jurídico, consultoria, auditoria)',
 'public-sector': 'Setor público',
 'research': 'Ensino e investigação',
 'sme': 'PME (pequena e média empresa)',
 'startup': 'Startup / empresa em formação'}

# ------------------------------------------------------------------- temas
THEMES = {'ai_act': 'EU AI Act',
 'ai_liability': 'Responsabilidade e prova em IA',
 'ai_office': 'European AI Office',
 'competition': 'Concorrência e mercados digitais',
 'consultation': 'Consultas públicas e agenda',
 'consumer': 'Consumidor e transparência',
 'copyright': 'Direitos de autor e conteúdo',
 'cybersecurity': 'Cibersegurança e resiliência',
 'data_act': 'Dados, cloud e infraestrutura digital',
 'dsa': 'Digital Services Act',
 'edpb': 'EDPB e proteção de dados em IA',
 'edps': 'EDPS e instituições da UE',
 'employment': 'Trabalho e emprego',
 'enforcement': 'Enforcement e sanções',
 'funding_innovation': 'Financiamento e inovação',
 'gpai': 'GPAI e modelos de fundação',
 'health_data': 'Dados de saúde e EHDS',
 'judicial': 'Jurisprudência e tribunais da UE',
 'public_sector': 'Setor público e contratação europeia'}

# ------------------------------------------------- metadados dos setores (M2)
SECTOR_META = {'adtech': {'en': 'AdTech',
            'focus': 'Publicidade programática, segmentação, medição e consentimento.',
            'name': 'AdTech'},
 'automotivo': {'en': 'Automotive',
                'focus': 'Veículos conectados, condução assistida, dados veiculares e segurança de produto.',
                'name': 'Automotivo'},
 'bancos': {'en': 'Banking',
            'focus': 'Crédito, scoring, decisões automatizadas, governança de modelos e controles internos.',
            'name': 'Bancos'},
 'ciberseguranca': {'en': 'Cybersecurity',
                    'focus': 'Detecção com IA, reporte de incidentes, vulnerabilidades e produtos com '
                             'elementos digitais.',
                    'name': 'Cibersegurança'},
 'cloud': {'en': 'Cloud',
           'focus': 'Infraestrutura de IA, soberania, segurança e responsabilidades na cadeia de '
                    'fornecimento.',
           'name': 'Cloud'},
 'data-centers': {'en': 'Data Centers',
                  'focus': 'Capacidade computacional, eficiência energética, água, soberania e localização '
                           'de dados.',
                  'name': 'Data Centers'},
 'ecommerce': {'en': 'E-commerce',
               'focus': 'Venda online, recomendação, publicidade direcionada e deveres de informação.',
               'name': 'E-commerce'},
 'educacao': {'en': 'Education',
              'focus': 'Avaliação, tutoria automatizada, integridade académica e proteção de menores.',
              'name': 'Educação'},
 'energia': {'en': 'Energy',
             'focus': 'IA em rede elétrica, trading, previsão e infraestrutura energética crítica.',
             'name': 'Energia'},
 'fintech': {'en': 'Fintech',
             'focus': 'Pagamentos, crédito digital, onboarding automatizado e prevenção a fraude.',
             'name': 'Fintech'},
 'hr-tech': {'en': 'HR Tech',
             'focus': 'Sistemas de RH com IA: triagem, avaliação, gestão de desempenho e monitorização.',
             'name': 'HR Tech'},
 'legaltech': {'en': 'LegalTech',
               'focus': 'Pesquisa jurídica, revisão documental, decisões assistidas e sigilo profissional.',
               'name': 'LegalTech'},
 'manufatura': {'en': 'Manufacturing',
                'focus': 'IA industrial, robótica, controlo de qualidade e obrigações de segurança de '
                         'máquinas.',
                'name': 'Manufatura'},
 'marketplaces': {'en': 'Marketplaces',
                  'focus': 'Intermediários online, deveres de informação, moderação e rastreabilidade de '
                           'vendedores.',
                  'name': 'Marketplaces'},
 'martech': {'en': 'MarTech',
             'focus': 'Automação de marketing, personalização e IA em decisão de cliente.',
             'name': 'MarTech'},
 'modelos-de-fundacao': {'en': 'Foundation Models',
                         'focus': 'Modelos de uso geral: documentação técnica, política de direitos '
                                  'autorais, avaliações e incidentes graves.',
                         'name': 'Modelos de Fundação (GPAI)'},
 'pharma': {'en': 'Pharma',
            'focus': 'Investigação clínica, farmacovigilância, dados de ensaios e IA em dispositivos '
                     'combinados.',
            'name': 'Pharma e Life Sciences'},
 'provedores-de-ia': {'en': 'AI Providers',
                      'focus': 'Empresas que colocam sistemas de IA no mercado da União, incluindo '
                               'assistentes e agentes.',
                      'name': 'Provedores de IA'},
 'recrutamento': {'en': 'Recruitment',
                  'focus': 'Triagem de candidaturas, ranking de currículos e decisões de emprego — alto '
                           'risco no AI Act.',
                  'name': 'Recrutamento e Seleção'},
 'saas': {'en': 'SaaS',
          'focus': 'Software como serviço que embute IA: transparência, contratos, dados de clientes e '
                   'conformidade.',
          'name': 'SaaS'},
 'saude': {'en': 'Healthcare',
           'focus': 'Dados de saúde, apoio à decisão clínica, software médico e sistemas de alto risco.',
           'name': 'Saúde'},
 'seguros': {'en': 'Insurance',
             'focus': 'Subscrição, precificação, sinistros e explicabilidade de decisões automatizadas.',
             'name': 'Seguros'},
 'telecom': {'en': 'Telecom',
             'focus': 'Redes, infraestrutura crítica, EECC e obrigações de segurança em serviços digitais.',
             'name': 'Telecomunicações'},
 'utilities': {'en': 'Utilities',
               'focus': 'Serviços essenciais, água, resíduos e ciber-resiliência de operadores essenciais.',
               'name': 'Utilities e Água'}}

SECTOR_FUNCTIONS = {'adtech': ['compliance', 'legal', 'ai-governance'],
 'automotivo': ['compliance', 'legal', 'ai-governance'],
 'bancos': ['risk', 'compliance', 'ai-governance', 'data-governance'],
 'ciberseguranca': ['cybersecurity', 'engineering', 'risk', 'compliance'],
 'cloud': ['engineering', 'cybersecurity', 'legal', 'procurement', 'ai-governance'],
 'data-centers': ['engineering', 'cybersecurity', 'strategy', 'compliance'],
 'ecommerce': ['compliance', 'legal', 'ai-governance'],
 'educacao': ['compliance', 'legal', 'ai-governance'],
 'energia': ['compliance', 'legal', 'ai-governance'],
 'fintech': ['compliance', 'privacy', 'product', 'risk'],
 'hr-tech': ['regulatory-affairs', 'compliance', 'dpo', 'ai-governance', 'legal'],
 'legaltech': ['compliance', 'legal', 'ai-governance'],
 'manufatura': ['compliance', 'legal', 'ai-governance'],
 'marketplaces': ['compliance', 'legal', 'ai-governance'],
 'martech': ['compliance', 'legal', 'ai-governance'],
 'modelos-de-fundacao': ['ai-governance', 'regulatory-affairs', 'engineering', 'legal', 'public-policy'],
 'pharma': ['clinical', 'compliance', 'dpo', 'legal'],
 'provedores-de-ia': ['ai-governance', 'regulatory-affairs', 'engineering', 'product', 'legal'],
 'recrutamento': ['regulatory-affairs', 'legal', 'compliance', 'ai-governance'],
 'saas': ['product', 'engineering', 'legal', 'compliance', 'dpo'],
 'saude': ['clinical', 'compliance', 'dpo', 'ai-governance'],
 'seguros': ['compliance', 'legal', 'ai-governance'],
 'telecom': ['compliance', 'legal', 'ai-governance'],
 'utilities': ['compliance', 'legal', 'ai-governance']}

SECTOR_COMPANY_TYPES = {'adtech': ['large-enterprise', 'sme'],
 'automotivo': ['large-enterprise', 'sme'],
 'bancos': ['large-enterprise', 'sme'],
 'ciberseguranca': ['ai-system-provider', 'large-enterprise', 'sme'],
 'cloud': ['cloud-infra', 'large-enterprise', 'sme'],
 'data-centers': ['cloud-infra', 'large-enterprise', 'sme'],
 'ecommerce': ['large-enterprise', 'sme'],
 'educacao': ['large-enterprise', 'sme'],
 'energia': ['large-enterprise', 'sme'],
 'fintech': ['large-enterprise', 'sme'],
 'hr-tech': ['large-enterprise', 'sme'],
 'legaltech': ['large-enterprise', 'sme'],
 'manufatura': ['large-enterprise', 'sme'],
 'marketplaces': ['large-enterprise', 'sme'],
 'martech': ['large-enterprise', 'sme'],
 'modelos-de-fundacao': ['gpai-provider', 'large-enterprise', 'startup', 'open-source'],
 'pharma': ['large-enterprise', 'sme'],
 'provedores-de-ia': ['ai-system-provider', 'large-enterprise', 'startup'],
 'recrutamento': ['large-enterprise', 'sme'],
 'saas': ['large-enterprise', 'sme'],
 'saude': ['health-provider', 'large-enterprise', 'sme'],
 'seguros': ['large-enterprise', 'sme'],
 'telecom': ['large-enterprise', 'sme'],
 'utilities': ['large-enterprise', 'sme']}

# ------------------------------------------------------- bibliotecas por tema
THEME_OBLIGATIONS = {'ai_act': ['Classificação de risco do sistema de IA e mapeamento do papel exercido (provedor, deployer, '
            'importador).',
            'Ativação das obrigações do capítulo aplicável ao nível de risco identificado.',
            'Registo de literacia em IA (Art. 4.º) para equipas que operam sistemas de IA.',
            'Evidência para avaliação de conformidade e documentação técnica quando aplicável.',
            'Acompanhamento das orientações e atos de execução aplicáveis antes de decisões de produto.',
            'Alinhamento da documentação interna com a terminologia e expectativas do AI Office.',
            'Documentação técnica do modelo e informação a fornecedores a jusante (Art. 53.º).',
            'Política de direitos de autor e resumo do conteúdo de treino quando aplicável.'],
 'ai_office': ['Verificação preventiva dos controlos equivalente aos que falharam na decisão publicada.',
               'Registo do risco e do plano de correção no sistema de compliance.',
               'Revisão contratual com fornecedores quando a decisão envolve terceiros.',
               'Base legal documentada para tratamento de dados pessoais em sistemas de IA.',
               'Avaliação de impacto sobre a proteção de dados (DPIA) quando exigida.',
               'Informação transparente sobre decisões automatizadas e revisão humana efetiva.',
               'Classificação de risco do sistema de IA e mapeamento do papel exercido (provedor, deployer, '
               'importador).',
               'Ativação das obrigações do capítulo aplicável ao nível de risco identificado.'],
 'competition': ['Acompanhamento das orientações e atos de execução aplicáveis antes de decisões de produto.',
                 'Alinhamento da documentação interna com a terminologia e expectativas do AI Office.',
                 'Participação em consultas e códigos de prática quando existir canal aberto.',
                 'Base legal documentada para tratamento de dados pessoais em sistemas de IA.',
                 'Avaliação de impacto sobre a proteção de dados (DPIA) quando exigida.',
                 'Informação transparente sobre decisões automatizadas e revisão humana efetiva.'],
 'consultation': ['Acompanhamento das orientações e atos de execução aplicáveis antes de decisões de produto.',
                  'Alinhamento da documentação interna com a terminologia e expectativas do AI Office.',
                  'Participação em consultas e códigos de prática quando existir canal aberto.',
                  'Base legal documentada para tratamento de dados pessoais em sistemas de IA.',
                  'Avaliação de impacto sobre a proteção de dados (DPIA) quando exigida.',
                  'Informação transparente sobre decisões automatizadas e revisão humana efetiva.',
                  'Preparação de posição institucional dentro do prazo oficial do feedback.',
                  'Registo da posição submetida e da evidência utilizada.'],
 'dsa': ['Verificação preventiva dos controlos equivalente aos que falharam na decisão publicada.',
         'Registo do risco e do plano de correção no sistema de compliance.',
         'Revisão contratual com fornecedores quando a decisão envolve terceiros.',
         'Base legal documentada para tratamento de dados pessoais em sistemas de IA.',
         'Avaliação de impacto sobre a proteção de dados (DPIA) quando exigida.',
         'Informação transparente sobre decisões automatizadas e revisão humana efetiva.'],
 'edpb': ['Verificação preventiva dos controlos equivalente aos que falharam na decisão publicada.',
          'Registo do risco e do plano de correção no sistema de compliance.',
          'Revisão contratual com fornecedores quando a decisão envolve terceiros.',
          'Base legal documentada para tratamento de dados pessoais em sistemas de IA.',
          'Avaliação de impacto sobre a proteção de dados (DPIA) quando exigida.',
          'Informação transparente sobre decisões automatizadas e revisão humana efetiva.',
          'Acompanhamento das orientações e atos de execução aplicáveis antes de decisões de produto.',
          'Alinhamento da documentação interna com a terminologia e expectativas do AI Office.'],
 'edps': ['Base legal documentada para tratamento de dados pessoais em sistemas de IA.',
          'Avaliação de impacto sobre a proteção de dados (DPIA) quando exigida.',
          'Informação transparente sobre decisões automatizadas e revisão humana efetiva.',
          'Minimização, retenção e segurança do conjunto de treino e dos dados de utilização.',
          'Acompanhamento das orientações e atos de execução aplicáveis antes de decisões de produto.',
          'Alinhamento da documentação interna com a terminologia e expectativas do AI Office.'],
 'enforcement': ['Verificação preventiva dos controlos equivalente aos que falharam na decisão publicada.',
                 'Registo do risco e do plano de correção no sistema de compliance.',
                 'Revisão contratual com fornecedores quando a decisão envolve terceiros.',
                 'Base legal documentada para tratamento de dados pessoais em sistemas de IA.',
                 'Avaliação de impacto sobre a proteção de dados (DPIA) quando exigida.',
                 'Informação transparente sobre decisões automatizadas e revisão humana efetiva.'],
 'funding_innovation': ['Requisitos de conformidade em contratos públicos, incluindo documentação e auditoria.',
                        'Obrigações específicas de utilização de IA por entidades públicas quando aplicáveis.',
                        'Preparação de posição institucional dentro do prazo oficial do feedback.',
                        'Registo da posição submetida e da evidência utilizada.',
                        'Verificação de elegibilidade e de deveres de reporte em financiamento europeu.',
                        'Candidaturas e utilização de sandboxes regulatórias quando disponíveis.'],
 'gpai': ['Classificação de risco do sistema de IA e mapeamento do papel exercido (provedor, deployer, '
          'importador).',
          'Ativação das obrigações do capítulo aplicável ao nível de risco identificado.',
          'Registo de literacia em IA (Art. 4.º) para equipas que operam sistemas de IA.',
          'Evidência para avaliação de conformidade e documentação técnica quando aplicável.',
          'Documentação técnica do modelo e informação a fornecedores a jusante (Art. 53.º).',
          'Política de direitos de autor e resumo do conteúdo de treino quando aplicável.'],
 'judicial': ['Base legal documentada para tratamento de dados pessoais em sistemas de IA.',
              'Avaliação de impacto sobre a proteção de dados (DPIA) quando exigida.',
              'Informação transparente sobre decisões automatizadas e revisão humana efetiva.',
              'Minimização, retenção e segurança do conjunto de treino e dos dados de utilização.',
              'Acompanhamento das orientações e atos de execução aplicáveis antes de decisões de produto.',
              'Alinhamento da documentação interna com a terminologia e expectativas do AI Office.'],
 'public_sector': ['Requisitos de conformidade em contratos públicos, incluindo documentação e auditoria.',
                   'Obrigações específicas de utilização de IA por entidades públicas quando aplicáveis.',
                   'Preparação de posição institucional dentro do prazo oficial do feedback.',
                   'Registo da posição submetida e da evidência utilizada.',
                   'Verificação de elegibilidade e de deveres de reporte em financiamento europeu.',
                   'Candidaturas e utilização de sandboxes regulatórias quando disponíveis.']}

THEME_RISKS = {'ai_act': ['Operar sistema de alto risco sem avaliação de conformidade documentada.',
            'Desconhecimento do papel regulatório efetivamente exercido na cadeia de valor.',
            'Perda de acesso ao mercado da UE para produto não conforme.',
            'Exposição a medidas da autoridade de supervisão do mercado.',
            'Tomar decisão de arquitetura com base em orientação desatualizada.',
            'Desalinhamento entre o produto e o entendimento da autoridade europeia.',
            'Falta de documentação que suporte as declarações comerciais do modelo.',
            'Dependência de fornecedor GPAI sem contrato que cubra informação regulatória.'],
 'ai_office': ['Repetir o padrão sancionado na sua própria operação.',
               'Multas de percentagem do volume de negócios global em casos de maior gravidade.',
               'Medidas corretivas que obrigam a alterar produto já em produção.',
               'Perda de confiança de clientes e de investidores após incidente público.',
               'Treino ou fine-tuning sem base legal documentada.',
               'Uso de web scraping e conteúdo pessoal sem avaliação registada.',
               'Operar sistema de alto risco sem avaliação de conformidade documentada.',
               'Desconhecimento do papel regulatório efetivamente exercido na cadeia de valor.'],
 'competition': ['Tomar decisão de arquitetura com base em orientação desatualizada.',
                 'Desalinhamento entre o produto e o entendimento da autoridade europeia.',
                 'Custo de retrabalho por implementação tardia de requisitos técnicos.',
                 'Treino ou fine-tuning sem base legal documentada.',
                 'Uso de web scraping e conteúdo pessoal sem avaliação registada.',
                 'Decisões automatizadas sem intervenção humana significativa.'],
 'consultation': ['Tomar decisão de arquitetura com base em orientação desatualizada.',
                  'Desalinhamento entre o produto e o entendimento da autoridade europeia.',
                  'Custo de retrabalho por implementação tardia de requisitos técnicos.',
                  'Treino ou fine-tuning sem base legal documentada.',
                  'Uso de web scraping e conteúdo pessoal sem avaliação registada.',
                  'Decisões automatizadas sem intervenção humana significativa.',
                  'Prazo de consulta perdido e ausência de influência sobre o desenho final.',
                  'Posição pública submetida sem validação jurídica e técnica interna.'],
 'dsa': ['Repetir o padrão sancionado na sua própria operação.',
         'Multas de percentagem do volume de negócios global em casos de maior gravidade.',
         'Medidas corretivas que obrigam a alterar produto já em produção.',
         'Perda de confiança de clientes e de investidores após incidente público.',
         'Treino ou fine-tuning sem base legal documentada.',
         'Uso de web scraping e conteúdo pessoal sem avaliação registada.'],
 'edpb': ['Repetir o padrão sancionado na sua própria operação.',
          'Multas de percentagem do volume de negócios global em casos de maior gravidade.',
          'Medidas corretivas que obrigam a alterar produto já em produção.',
          'Perda de confiança de clientes e de investidores após incidente público.',
          'Treino ou fine-tuning sem base legal documentada.',
          'Uso de web scraping e conteúdo pessoal sem avaliação registada.',
          'Tomar decisão de arquitetura com base em orientação desatualizada.',
          'Desalinhamento entre o produto e o entendimento da autoridade europeia.'],
 'edps': ['Treino ou fine-tuning sem base legal documentada.',
          'Uso de web scraping e conteúdo pessoal sem avaliação registada.',
          'Decisões automatizadas sem intervenção humana significativa.',
          'Transferências internacionais sem mecanismo válido.',
          'Tomar decisão de arquitetura com base em orientação desatualizada.',
          'Desalinhamento entre o produto e o entendimento da autoridade europeia.'],
 'enforcement': ['Repetir o padrão sancionado na sua própria operação.',
                 'Multas de percentagem do volume de negócios global em casos de maior gravidade.',
                 'Medidas corretivas que obrigam a alterar produto já em produção.',
                 'Perda de confiança de clientes e de investidores após incidente público.',
                 'Treino ou fine-tuning sem base legal documentada.',
                 'Uso de web scraping e conteúdo pessoal sem avaliação registada.'],
 'funding_innovation': ['Perder concurso por documentação de conformidade incompleta.',
                        'Assumir obrigações contratuais não suportáveis operacionalmente.',
                        'Prazo de consulta perdido e ausência de influência sobre o desenho final.',
                        'Posição pública submetida sem validação jurídica e técnica interna.',
                        'Perder janela de candidatura ou incumprir deveres de reporte de subsídio.'],
 'gpai': ['Operar sistema de alto risco sem avaliação de conformidade documentada.',
          'Desconhecimento do papel regulatório efetivamente exercido na cadeia de valor.',
          'Perda de acesso ao mercado da UE para produto não conforme.',
          'Exposição a medidas da autoridade de supervisão do mercado.',
          'Falta de documentação que suporte as declarações comerciais do modelo.',
          'Dependência de fornecedor GPAI sem contrato que cubra informação regulatória.'],
 'judicial': ['Treino ou fine-tuning sem base legal documentada.',
              'Uso de web scraping e conteúdo pessoal sem avaliação registada.',
              'Decisões automatizadas sem intervenção humana significativa.',
              'Transferências internacionais sem mecanismo válido.',
              'Tomar decisão de arquitetura com base em orientação desatualizada.',
              'Desalinhamento entre o produto e o entendimento da autoridade europeia.'],
 'public_sector': ['Perder concurso por documentação de conformidade incompleta.',
                   'Assumir obrigações contratuais não suportáveis operacionalmente.',
                   'Prazo de consulta perdido e ausência de influência sobre o desenho final.',
                   'Posição pública submetida sem validação jurídica e técnica interna.',
                   'Perder janela de candidatura ou incumprir deveres de reporte de subsídio.']}

THEME_OPPORTUNITIES = {'ai_act': ['Padronização antecipada do inventário de sistemas de IA como ativo de governança.',
            'Posicionamento como fornecedor conforme em processos de procurement de clientes regulados.',
            'Reaproveitamento do trabalho de conformidade para due diligence de clientes e investidores.',
            'Contribuir para o desenho das regras através de consultas e códigos de prática.',
            'Usar orientações oficiais como referência de garantia de qualidade interna.',
            'Diferenciação via documentação e transparência creditável perante clientes regulados.',
            'Antecipação de exigências de procurement corporativo e do setor público.',
            'Posição de referência em avaliação e mitigação de risco de modelo.'],
 'ai_office': ['Utilizar as decisões publicadas como teste-padrão interno antes de uma auditoria.',
               'Demonstrar diligência documentada a clientes regulados e seguradoras.',
               'Redução de risco antes de escalar o produto para novos mercados.',
               'Uso de orientações do EDPB como argumento de confiança em vendas a clientes regulados.',
               'Contribuir para o desenho das regras através de consultas e códigos de prática.',
               'Usar orientações oficiais como referência de garantia de qualidade interna.',
               'Padronização antecipada do inventário de sistemas de IA como ativo de governança.',
               'Posicionamento como fornecedor conforme em processos de procurement de clientes regulados.'],
 'competition': ['Contribuir para o desenho das regras através de consultas e códigos de prática.',
                 'Usar orientações oficiais como referência de garantia de qualidade interna.',
                 'Redução de risco antes de escalar o produto para novos mercados.',
                 'Uso de orientações do EDPB como argumento de confiança em vendas a clientes regulados.',
                 'Parcerias de dados estruturadas de forma defensável.',
                 'Influência documentada sobre atos em preparação.'],
 'consultation': ['Contribuir para o desenho das regras através de consultas e códigos de prática.',
                  'Usar orientações oficiais como referência de garantia de qualidade interna.',
                  'Redução de risco antes de escalar o produto para novos mercados.',
                  'Uso de orientações do EDPB como argumento de confiança em vendas a clientes regulados.',
                  'Parcerias de dados estruturadas de forma defensável.',
                  'Influência documentada sobre atos em preparação.',
                  'Relacionamento institucional com a Comissão e com o AI Office.',
                  'Posição favorável em concursos que valorizam conformidade demonstrável.'],
 'dsa': ['Utilizar as decisões publicadas como teste-padrão interno antes de uma auditoria.',
         'Demonstrar diligência documentada a clientes regulados e seguradoras.',
         'Redução de risco antes de escalar o produto para novos mercados.',
         'Uso de orientações do EDPB como argumento de confiança em vendas a clientes regulados.',
         'Contribuir para o desenho das regras através de consultas e códigos de prática.',
         'Usar orientações oficiais como referência de garantia de qualidade interna.'],
 'edpb': ['Utilizar as decisões publicadas como teste-padrão interno antes de uma auditoria.',
          'Demonstrar diligência documentada a clientes regulados e seguradoras.',
          'Redução de risco antes de escalar o produto para novos mercados.',
          'Uso de orientações do EDPB como argumento de confiança em vendas a clientes regulados.',
          'Contribuir para o desenho das regras através de consultas e códigos de prática.',
          'Usar orientações oficiais como referência de garantia de qualidade interna.',
          'Parcerias de dados estruturadas de forma defensável.',
          'Influência documentada sobre atos em preparação.'],
 'edps': ['Redução de risco antes de escalar o produto para novos mercados.',
          'Uso de orientações do EDPB como argumento de confiança em vendas a clientes regulados.',
          'Contribuir para o desenho das regras através de consultas e códigos de prática.',
          'Usar orientações oficiais como referência de garantia de qualidade interna.',
          'Segurança jurídica acrescida para decisões de produto já alinhadas com a jurisprudência.',
          'Uso das decisões do EDPS como antecipação de padrões de exigência do setor público.'],
 'enforcement': ['Utilizar as decisões publicadas como teste-padrão interno antes de uma auditoria.',
                 'Demonstrar diligência documentada a clientes regulados e seguradoras.',
                 'Redução de risco antes de escalar o produto para novos mercados.',
                 'Uso de orientações do EDPB como argumento de confiança em vendas a clientes regulados.',
                 'Contribuir para o desenho das regras através de consultas e códigos de prática.',
                 'Usar orientações oficiais como referência de garantia de qualidade interna.'],
 'funding_innovation': ['Posição favorável em concursos que valorizam conformidade demonstrável.',
                        'Influência documentada sobre atos em preparação.',
                        'Relacionamento institucional com a Comissão e com o AI Office.',
                        'Acesso a financiamento para conformidade e desenvolvimento.',
                        'Uso de sandbox regulatória para reduzir incerteza de produto.'],
 'gpai': ['Padronização antecipada do inventário de sistemas de IA como ativo de governança.',
          'Posicionamento como fornecedor conforme em processos de procurement de clientes regulados.',
          'Reaproveitamento do trabalho de conformidade para due diligence de clientes e investidores.',
          'Diferenciação via documentação e transparência creditável perante clientes regulados.',
          'Antecipação de exigências de procurement corporativo e do setor público.',
          'Posição de referência em avaliação e mitigação de risco de modelo.'],
 'judicial': ['Redução de risco antes de escalar o produto para novos mercados.',
              'Uso de orientações do EDPB como argumento de confiança em vendas a clientes regulados.',
              'Contribuir para o desenho das regras através de consultas e códigos de prática.',
              'Usar orientações oficiais como referência de garantia de qualidade interna.',
              'Segurança jurídica acrescida para decisões de produto já alinhadas com a jurisprudência.',
              'Uso das decisões do EDPS como antecipação de padrões de exigência do setor público.'],
 'public_sector': ['Posição favorável em concursos que valorizam conformidade demonstrável.',
                   'Influência documentada sobre atos em preparação.',
                   'Relacionamento institucional com a Comissão e com o AI Office.',
                   'Acesso a financiamento para conformidade e desenvolvimento.',
                   'Uso de sandbox regulatória para reduzir incerteza de produto.']}

THEME_ACTIONS = {'ai_act': [('Inventariar sistemas de IA por caso de uso, risco e papel regulatório.', 'ai-governance', 'Alta'),
            ('Confirmar no texto oficial do AI Act quais obrigações são aplicáveis ao seu caso.',
             'ai-governance',
             'Alta'),
            ('Nomear responsável executivo e orçamento para a trilha de conformidade.', 'ai-governance', 'Alta'),
            ('Documentar decisões de classificação e guardar a evidência.', 'ai-governance', 'Alta'),
            ('Assinar as atualizações do AI Office e do registo oficial antes de cada release relevante.',
             'regulatory-affairs',
             'Alta'),
            ('Registar em ata a versão da orientação usada para decidir.', 'regulatory-affairs', 'Alta'),
            ('Obter do fornecedor a documentação técnica e os termos de uso atualizados.',
             'ai-governance',
             'Alta'),
            ('Registar a versão do modelo usada em cada produto e a data de mudança.', 'ai-governance', 'Alta')],
 'ai_office': [('Atualizar a matriz de risco com o padrão sancionado nesta decisão.', 'compliance', 'Alta'),
               ('Testar o controlo correspondente no seu próprio processo e registar o resultado.',
                'compliance',
                'Alta'),
               ('Levar o caso concreto à reunião de compliance com responsável nomeado.', 'compliance', 'Alta'),
               ('Mapear as bases legais de cada caso de uso de IA que trata dados pessoais.', 'dpo', 'Alta'),
               ('Atualizar a DPIA para os casos de uso afetados pela orientação mais recente.', 'dpo', 'Alta'),
               ('Formar produto e marketing sobre limites de uso de dados pessoais.', 'dpo', 'Alta'),
               ('Inventariar sistemas de IA por caso de uso, risco e papel regulatório.', 'ai-governance', 'Alta'),
               ('Confirmar no texto oficial do AI Act quais obrigações são aplicáveis ao seu caso.',
                'ai-governance',
                'Alta')],
 'competition': [('Assinar as atualizações do AI Office e do registo oficial antes de cada release relevante.',
                  'regulatory-affairs',
                  'Alta'),
                 ('Registar em ata a versão da orientação usada para decidir.', 'regulatory-affairs', 'Alta'),
                 ('Envolver produto e jurídico na leitura de novas orientações.', 'regulatory-affairs', 'Alta'),
                 ('Mapear as bases legais de cada caso de uso de IA que trata dados pessoais.', 'dpo', 'Alta'),
                 ('Atualizar a DPIA para os casos de uso afetados pela orientação mais recente.', 'dpo', 'Alta'),
                 ('Formar produto e marketing sobre limites de uso de dados pessoais.', 'dpo', 'Alta')],
 'consultation': [('Assinar as atualizações do AI Office e do registo oficial antes de cada release relevante.',
                   'regulatory-affairs',
                   'Alta'),
                  ('Registar em ata a versão da orientação usada para decidir.', 'regulatory-affairs', 'Alta'),
                  ('Envolver produto e jurídico na leitura de novas orientações.', 'regulatory-affairs', 'Alta'),
                  ('Mapear as bases legais de cada caso de uso de IA que trata dados pessoais.', 'dpo', 'Alta'),
                  ('Atualizar a DPIA para os casos de uso afetados pela orientação mais recente.', 'dpo', 'Alta'),
                  ('Formar produto e marketing sobre limites de uso de dados pessoais.', 'dpo', 'Alta'),
                  ('Verificar na página oficial da consulta o prazo e o formulário de submissão.',
                   'public-policy',
                   'Média'),
                  ('Validar internamente a posição antes de submeter.', 'public-policy', 'Média')],
 'dsa': [('Atualizar a matriz de risco com o padrão sancionado nesta decisão.', 'compliance', 'Alta'),
         ('Testar o controlo correspondente no seu próprio processo e registar o resultado.',
          'compliance',
          'Alta'),
         ('Levar o caso concreto à reunião de compliance com responsável nomeado.', 'compliance', 'Alta'),
         ('Mapear as bases legais de cada caso de uso de IA que trata dados pessoais.', 'dpo', 'Alta'),
         ('Atualizar a DPIA para os casos de uso afetados pela orientação mais recente.', 'dpo', 'Alta'),
         ('Formar produto e marketing sobre limites de uso de dados pessoais.', 'dpo', 'Alta')],
 'edpb': [('Atualizar a matriz de risco com o padrão sancionado nesta decisão.', 'compliance', 'Alta'),
          ('Testar o controlo correspondente no seu próprio processo e registar o resultado.',
           'compliance',
           'Alta'),
          ('Levar o caso concreto à reunião de compliance com responsável nomeado.', 'compliance', 'Alta'),
          ('Mapear as bases legais de cada caso de uso de IA que trata dados pessoais.', 'dpo', 'Alta'),
          ('Atualizar a DPIA para os casos de uso afetados pela orientação mais recente.', 'dpo', 'Alta'),
          ('Formar produto e marketing sobre limites de uso de dados pessoais.', 'dpo', 'Alta'),
          ('Assinar as atualizações do AI Office e do registo oficial antes de cada release relevante.',
           'regulatory-affairs',
           'Alta'),
          ('Registar em ata a versão da orientação usada para decidir.', 'regulatory-affairs', 'Alta')],
 'edps': [('Mapear as bases legais de cada caso de uso de IA que trata dados pessoais.', 'dpo', 'Alta'),
          ('Atualizar a DPIA para os casos de uso afetados pela orientação mais recente.', 'dpo', 'Alta'),
          ('Formar produto e marketing sobre limites de uso de dados pessoais.', 'dpo', 'Alta'),
          ('Assinar as atualizações do AI Office e do registo oficial antes de cada release relevante.',
           'regulatory-affairs',
           'Alta'),
          ('Registar em ata a versão da orientação usada para decidir.', 'regulatory-affairs', 'Alta'),
          ('Envolver produto e jurídico na leitura de novas orientações.', 'regulatory-affairs', 'Alta')],
 'enforcement': [('Atualizar a matriz de risco com o padrão sancionado nesta decisão.', 'compliance', 'Alta'),
                 ('Testar o controlo correspondente no seu próprio processo e registar o resultado.',
                  'compliance',
                  'Alta'),
                 ('Levar o caso concreto à reunião de compliance com responsável nomeado.', 'compliance', 'Alta'),
                 ('Mapear as bases legais de cada caso de uso de IA que trata dados pessoais.', 'dpo', 'Alta'),
                 ('Atualizar a DPIA para os casos de uso afetados pela orientação mais recente.', 'dpo', 'Alta'),
                 ('Formar produto e marketing sobre limites de uso de dados pessoais.', 'dpo', 'Alta')],
 'funding_innovation': [('Preparar dossiê de conformidade reutilizável para concursos públicos da UE e nacionais.',
                         'public-policy',
                         'Média'),
                        ('Verificar na página oficial da consulta o prazo e o formulário de submissão.',
                         'public-policy',
                         'Média'),
                        ('Validar internamente a posição antes de submeter.', 'public-policy', 'Média'),
                        ('Registar o número de referência da contribuição submetida.', 'public-policy', 'Média'),
                        ('Verificar no portal oficial a elegibilidade da sua organização e o prazo da chamada.',
                         'strategy',
                         'Média'),
                        ('Registar os deveres de reporte assumidos com o financiamento.', 'strategy', 'Média')],
 'gpai': [('Inventariar sistemas de IA por caso de uso, risco e papel regulatório.', 'ai-governance', 'Alta'),
          ('Confirmar no texto oficial do AI Act quais obrigações são aplicáveis ao seu caso.',
           'ai-governance',
           'Alta'),
          ('Nomear responsável executivo e orçamento para a trilha de conformidade.', 'ai-governance', 'Alta'),
          ('Documentar decisões de classificação e guardar a evidência.', 'ai-governance', 'Alta'),
          ('Obter do fornecedor a documentação técnica e os termos de uso atualizados.', 'ai-governance', 'Alta'),
          ('Registar a versão do modelo usada em cada produto e a data de mudança.', 'ai-governance', 'Alta')],
 'judicial': [('Mapear as bases legais de cada caso de uso de IA que trata dados pessoais.', 'dpo', 'Alta'),
              ('Atualizar a DPIA para os casos de uso afetados pela orientação mais recente.', 'dpo', 'Alta'),
              ('Formar produto e marketing sobre limites de uso de dados pessoais.', 'dpo', 'Alta'),
              ('Assinar as atualizações do AI Office e do registo oficial antes de cada release relevante.',
               'regulatory-affairs',
               'Alta'),
              ('Registar em ata a versão da orientação usada para decidir.', 'regulatory-affairs', 'Alta'),
              ('Envolver produto e jurídico na leitura de novas orientações.', 'regulatory-affairs', 'Alta')],
 'public_sector': [('Preparar dossiê de conformidade reutilizável para concursos públicos da UE e nacionais.',
                    'public-policy',
                    'Média'),
                   ('Verificar na página oficial da consulta o prazo e o formulário de submissão.',
                    'public-policy',
                    'Média'),
                   ('Validar internamente a posição antes de submeter.', 'public-policy', 'Média'),
                   ('Registar o número de referência da contribuição submetida.', 'public-policy', 'Média'),
                   ('Verificar no portal oficial a elegibilidade da sua organização e o prazo da chamada.',
                    'strategy',
                    'Média'),
                   ('Registar os deveres de reporte assumidos com o financiamento.', 'strategy', 'Média')]}
